// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXI5IV4QH3Gya-z8Hpj7xDmySrtK9t5d4',
    appId: '1:1058338810622:web:3e0191d4da13ab368113af',
    messagingSenderId: '1058338810622',
    projectId: 'moodle-mobile-58061',
    authDomain: 'moodle-mobile-58061.firebaseapp.com',
    storageBucket: 'moodle-mobile-58061.appspot.com',
    measurementId: 'G-58QM38TGVR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIY28dYC823SaNtaICsUhBbv7vejsLrDw',
    appId: '1:1058338810622:android:d84eb981f8f1dd068113af',
    messagingSenderId: '1058338810622',
    projectId: 'moodle-mobile-58061',
    storageBucket: 'moodle-mobile-58061.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH6uRpAgTqDzei8EwG9qmAB4lBH_j3lSU',
    appId: '1:1058338810622:ios:e72924a74afa60e38113af',
    messagingSenderId: '1058338810622',
    projectId: 'moodle-mobile-58061',
    storageBucket: 'moodle-mobile-58061.appspot.com',
    iosClientId: '1058338810622-3t7no8m3fm8ttpfv8cvnnh9gqogghq1d.apps.googleusercontent.com',
    iosBundleId: 'com.example.moodleMobile',
  );
}
